services:
  example:
    image: example
    container_name: example
    restart: always
    user: "0:0"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/example
      - ./data:/data
    expose:
      - 80
      - 443
    env_file:
      - .env